### ISSUE TITLE
"Large" AP gain incorrectly calculating.

### ISSUE THREAD

**Issue by spectrrr** [aq2lx/twdrts#1]
**Brilliant calculator, well made!** 

One issue -- although the wiki and most resources report Large weapon AP gain as **7**, this is actually incorrect and easy to prove through testing. The correct value is **6.5**. 

Although the game rounds up the _display_ of any decimal value >.5 and uses the displayed value to calculate rushes, _the precise value is maintained_ in a variable and used from one turn to the next in the coding. 

**PROOF:** Equip a weapon that gives a "large" bonus on a toon with an unleveled AR (100+) and no AR leaderskill on the team. Go fight some walkers. 

Round1: 26.5 (display 27)
Round2: 53 (display 53)
Round3: 79.5 (display 80)
Round4: 106 (display 106)
Round5: 132.5 (display 133)

If 7 were the correct value, then 3*27=81 and 5*27=135. But it won't. Try it! 

**When does this minor difference in ap make a difference? With 45 and 44 AR toons on defense behind a medium lead:**

_(20+5+6.5)*1.4 = 44.1_ 
rounds down to 44, NOT enough to fire a 45 AR toon on defense round1. 

_(20+5+7)*1.4 = 44.8_
rounds up to 45, calculator incorrectly reports that a 45 AR toon will fire round1 on defense behind a medium lead with a large weapon.

**Comment by aq2lx** [comment]
Thanks for report, fixed :)
